/** Paradice Forge — story tree. Soft-launch a few; one new world every few months. */
window.FORGE_WORLDS = {
  cadence: "One new world every ~3 months after the soft launch. The shop stays Armageddon until a branch is marked open.",
  softLaunch: ["armageddon", "lumora", "weightless"],
  worlds: [
    {
      id: "armageddon",
      name: "Armageddon desk",
      kind: "miniatures · YouTube · shop",
      status: "open",
      when: "Soft launch now — now",
      blurb: "Paradice Miniatures. Blood Angels / Knights of the Chalice vs Orks. This is the only branch with a test shop, 2k prices, STLs, and singles.",
      href: "shop.html",
      cta: "Open the shop",
    },
    {
      id: "lumora",
      name: "Lumora — The Eternal Gauntlet",
      kind: "game · book · Equinox",
      status: "next",
      when: "Next drop — after eyes-on playtest",
      blurb: "Meadow, castle, Equinox fragments. Playtest spine is built. First Forge artifact: a public play slice or Equinox print — not a second empty store.",
      href: "adventure.html",
      cta: "Channel first · shop later",
    },
    {
      id: "weightless",
      name: "Weightless Love",
      kind: "book",
      status: "soft",
      when: "Soft launch — chapter 1 as the door",
      blurb: "Manuscript in BookWriter. The Forge drop is one public chapter, not the whole novel dumped at once.",
      href: "creations.html#weightless",
      cta: "Queued",
    },
    {
      id: "follow-heart",
      name: "Follow your heart",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "Full draft exists. Waits its season so Armageddon and Lumora don’t compete the same month.",
      href: "creations.html#follow-heart",
      cta: "On the shelf",
    },
    {
      id: "echos",
      name: "The Echos",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "Story on the shelf. Same rule: one Forge door when its month comes.",
    },
    {
      id: "moon",
      name: "Remembrance of the Moon",
      kind: "book · audiobook",
      status: "shelf",
      when: "Later season",
      blurb: "Chapters + audiobook work already started. Seasonal drop, not a second storefront.",
    },
    {
      id: "guardians",
      name: "The Guardian’s Choice",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "On the shelf.",
    },
    {
      id: "evolution",
      name: "The Evolution",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "On the shelf.",
    },
    {
      id: "soul-engine",
      name: "Soul Engine",
      kind: "book · audio",
      status: "shelf",
      when: "Later season",
      blurb: "On the shelf.",
    },
    {
      id: "shadow",
      name: "Shadow Realms",
      kind: "book · screenplay",
      status: "shelf",
      when: "Later season",
      blurb: "Includes Reborn. Screenplay path exists — still one seasonal door.",
    },
    {
      id: "spark",
      name: "Ascent of the Eternal Spark",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "On the shelf.",
    },
    {
      id: "international",
      name: "International Hearts",
      kind: "book",
      status: "shelf",
      when: "Later season",
      blurb: "On the shelf.",
    },
    {
      id: "tarot",
      name: "CryptoTarot",
      kind: "app · oracle",
      status: "shelf",
      when: "Field of gold",
      blurb: "Product exists as a lane. Not a Forge shop until its season.",
    },
    {
      id: "maui",
      name: "MTG Maui",
      kind: "game",
      status: "shelf",
      when: "Field of gold",
      blurb: "Maui table. Activates when it is a dream-board week, not a side tab.",
    },
  ],
  seasons: [
    { id: "s0", name: "Soft launch", when: "Now", drop: "Armageddon shop (test) + tree on the site" },
    { id: "s1", name: "Season 1", when: "Next ~3 months", drop: "Lumora — first public play / Equinox artifact" },
    { id: "s2", name: "Season 2", when: "+3 months", drop: "Weightless Love — chapter 1 door" },
    { id: "s3", name: "Season 3", when: "+3 months", drop: "One book from the shelf (you pick that month)" },
    { id: "s4", name: "Season 4", when: "+3 months", drop: "Next shelf world — still one, not five" },
  ],
};
