/** Paradice Forge — test catalog. Edit prices here. Checkout is not live. */
window.FORGE_CATALOG = {
  note:
    "Test prices. Plastic costs are ballpark US hobby retail and drift. Painted lots are GW kits Aaron buys, builds, and paints — not official merchandise. STLs are original Forge files only (no GW sculpts).",

  lanes: [
    {
      id: "stl",
      name: "Digital STLs",
      blurb: "Original Forge files. Instant download. Personal use. Never GW sculpts.",
    },
    {
      id: "army",
      name: "Painted armies",
      blurb: "One-of-one trays from the desk. Full 2k lists. You-ship.",
    },
    {
      id: "hero",
      name: "Heroes & singles",
      blurb: "Centerpiece models — shelf or painted to order. Separate from army trays.",
    },
    {
      id: "terrain",
      name: "Printed & painted terrain",
      blurb: "Physical prints of Forge STLs. Unpainted dropship or custom painted.",
    },
  ],

  splitWhy: [
    {
      keep: "STLs",
      why: "Digital, repeatable, no postage, original sculpts, Lemon Squeezy.",
    },
    {
      keep: "Armies & singles",
      why: "Unique painted GW plastic. One owner. Pirate Ship. Photos of the actual tray.",
    },
    {
      keep: "Printed terrain",
      why: "Repeatable physical of YOUR files. Farm dropship. Unpainted default.",
    },
    {
      keep: "Painted custom terrain",
      why: "Commission on a Forge print. Priced like art, not like an STL.",
    },
  ],

  guides: [
    {
      id: "ba-2k",
      sku: "LPF-ARMY-BA2K",
      name: "Blood Angels — Liberator Spine",
      points: 2000,
      match: "Strike Force · recommended viewer list",
      plasticEst: 980,
      greyEst: 1280,
      paintedEst: 2850,
      ship: "You-ship from Hawaii. CONUS quoted before payment.",
      status: "test",
      units: [
        { role: "Fast / secondaries", unit: "Jump Assault Intercessors ×5", plastic: 85 },
        { role: "Fast hammer", unit: "Captain + Sanguinary Guard", plastic: 110 },
        { role: "Support", unit: "Sanguinary Priest", plastic: 42 },
        { role: "Mid brick", unit: "Assault Terminators ×10 (LC + TH/SS)", plastic: 220 },
        { role: "Firepower", unit: "Redemptor Dreadnought (owned)", plastic: 85 },
        { role: "Objectives", unit: "Assault Intercessors ×10+ (ground)", plastic: 60 },
        { role: "Screen", unit: "Scouts ×5", plastic: 45 },
        { role: "Leaders", unit: "Chaplains ×2 (until Lemartes)", plastic: 80 },
        { role: "Core", unit: "Combat Patrol box (converts + Captain)", plastic: 170 },
      ],
      note: "Points and kit prices drift. Rebuild in-app before a list-tour. Termies are OOP — used-market estimate.",
    },
    {
      id: "ork-2k",
      sku: "LPF-ARMY-ORK2K",
      name: "Orks — Green Tide + Iron",
      points: 2000,
      match: "Strike Force · rival Armageddon army",
      plasticEst: 860,
      greyEst: 1120,
      paintedEst: 2450,
      ship: "You-ship from Hawaii. CONUS quoted before payment.",
      status: "test",
      units: [
        { role: "Warlord", unit: "Warboss (claw) · Ghaz flex", plastic: 120 },
        { role: "Tide", unit: "Boyz ×2–3 bricks", plastic: 110 },
        { role: "Buff", unit: "Bannernob", plastic: 40 },
        { role: "Psyker", unit: "Weirdboy", plastic: 38 },
        { role: "Lieutenant", unit: "Bigboss", plastic: 42 },
        { role: "Sustain", unit: "Painboy", plastic: 40 },
        { role: "Fast", unit: "Wartrakk ± Stormboyz", plastic: 70 },
        { role: "Dakka", unit: "Big Mek DakkaRig", plastic: 55 },
        { role: "Centerpiece", unit: "Battlewagon (owned) — kitbash", plastic: 80 },
        { role: "Core", unit: "Armageddon Ork box", plastic: 165 },
      ],
      note: "Ghaz embark-in-wagon only if keywords allow — see army legal note. Wagon kitbash still to film.",
    },
  ],

  products: [
    {
      sku: "LPF-STL-TA2",
      lane: "stl",
      name: "Ruined nave / shrine",
      tag: "STL pack #1 pick",
      price: 28,
      status: "scaffolding",
      blurb: "Broken nave, collapsed roof, printable FDM. Original Forge sculpt — gothic sci-fi, not a named shrine.",
      includes: ["STL zip (personal use)", "License TXT", "FDM cut notes"],
      ship: "Digital — no postage",
    },
    {
      sku: "LPF-STL-TA1",
      lane: "stl",
      name: "Void-wreck hull",
      tag: "STL",
      price: 32,
      status: "idea",
      blurb: "Crashed hull ribs and hatches. Modular halves. Sky-crusade centerpiece.",
      includes: ["STL zip (personal use)", "License TXT"],
      ship: "Digital — no postage",
    },
    {
      sku: "LPF-STL-TA3",
      lane: "stl",
      name: "Scrap keep",
      tag: "STL",
      price: 30,
      status: "idea",
      blurb: "Riveted plates, gun ports, yellow-rust industrial keep. Matches the Armageddon mob read.",
      includes: ["STL zip (personal use)", "License TXT"],
      ship: "Digital — no postage",
    },
    {
      sku: "LPF-STL-C3",
      lane: "stl",
      name: "Forge dice tray",
      tag: "STL · desk",
      price: 12,
      status: "idea",
      blurb: "Paradice Forge mark. Paradice = dice. Small file, easy FDM.",
      includes: ["STL zip (personal use)"],
      ship: "Digital — no postage",
    },
    {
      sku: "LPF-ARMY-BA2K",
      lane: "army",
      name: "Blood Angels 2,000 pts — Liberator Spine",
      tag: "Painted tray · test",
      price: 2850,
      status: "test",
      blurb: "Table-ready Strike Force from the Armageddon desk. Jumps, Guard, Redemptor, Termies. One-of-one — photos of this tray when it exists.",
      includes: ["Full 2k as listed on the price guide", "Magnetized where practical", "Hawaii origin ship quote"],
      ship: "You-ship · not dropship",
      hrefGuide: "price-guide.html#ba-2k",
    },
    {
      sku: "LPF-ARMY-ORK2K",
      lane: "army",
      name: "Orks 2,000 pts — Green Tide + Wagon",
      tag: "Painted tray · test",
      price: 2450,
      status: "test",
      blurb: "Rival Armageddon 2k: Boyz tide, DakkaRig, owned Battlewagon kitbash path. Painted unified green / yellow-rust when the paint episode lands.",
      includes: ["Full 2k as listed on the price guide", "Wagon as 'Ard Case kitbash (legal weapons)", "Hawaii origin ship quote"],
      ship: "You-ship · not dropship",
      hrefGuide: "price-guide.html#ork-2k",
    },
    {
      sku: "LPF-HERO-TYRANT",
      lane: "hero",
      name: "Hive Tyrant with wings",
      tag: "Single · to order",
      price: 185,
      status: "test",
      blurb: "Example hero single: flying hive tyrant, painted to order from a retail kit. Not an STL. Not part of the BA/Ork YouTube spine — a desk commission SKU.",
      includes: ["Retail kit (new)", "Wings built", "Painted to an agreed scheme", "You-ship"],
      ship: "You-ship · 2–4 week paint window (test)",
    },
    {
      sku: "LPF-HERO-LEMARTES",
      lane: "hero",
      name: "Lemartes",
      tag: "Wishlist hero",
      price: 165,
      status: "idea",
      blurb: "BA jump chaplain — the desk wants him to replace interim Chaplains. Painted single when owned.",
      includes: ["Retail kit when sourced", "Channel scheme (BA or KotC helmet lock)"],
      ship: "You-ship when painted",
    },
    {
      sku: "LPF-HERO-JUMPCAP",
      lane: "hero",
      name: "Jump Captain (thunder hammer / shield)",
      tag: "Wishlist hero",
      price: 145,
      status: "idea",
      blurb: "Fast hammer for the Liberator Spine. Convert or kit — painted single.",
      includes: ["Built jump captain", "BA / KotC scheme"],
      ship: "You-ship when painted",
    },
    {
      sku: "LPF-HERO-GHAZ",
      lane: "hero",
      name: "Ghazghkull — boss silhouette",
      tag: "Ork centerpiece",
      price: 220,
      status: "idea",
      blurb: "Blacker boss paint. Throne / open-platform look. Embark-in-wagon only if keywords allow.",
      includes: ["Retail Ghaz", "Painted black-boss scheme"],
      ship: "You-ship when painted",
    },
    {
      sku: "LPF-HERO-DANTE",
      lane: "hero",
      name: "Dante / Sanguinor (luxury)",
      tag: "Idea",
      price: 240,
      status: "idea",
      blurb: "Parade / 3k fluff heroes. Not promised on camera. Listed so the shop can price a single if one is painted.",
      includes: ["Retail kit", "Display paint"],
      ship: "You-ship",
    },
    {
      sku: "LPF-PHY-TA2",
      lane: "terrain",
      name: "Ruined nave — unpainted print",
      tag: "Physical · farm",
      price: 89,
      status: "idea",
      blurb: "Dropshipped FDM of the Forge nave STL. Grey, cleaned, unsanded. Repeatable. Not a painted commission.",
      includes: ["Physical print of LPF-STL-TA2", "Farm ships CONUS", "Personal-use object"],
      ship: "Filament Farm / Printie dropship",
    },
    {
      sku: "LPF-PHY-TA2P",
      lane: "terrain",
      name: "Ruined nave — painted centerpiece",
      tag: "Custom painted",
      price: 320,
      status: "idea",
      blurb: "Same print, table-ready paint. Priced as art on terrain — not as an STL and not as an army.",
      includes: ["Print + paint", "You-ship or farm+return", "Photos of the actual piece"],
      ship: "You-ship (commission)",
    },
  ],
};
